---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: external-dns
spec:
  selector:
    matchLabels:
      app: external-dns
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
        - name: external-dns
          image: registry.opensource.zalan.do/teapot/external-dns:latest
          args:
            - --source=ingress
            - --domain-filter=PLACEHOLDER_DOMAIN
            - --source=service
            - --provider=cloudflare
            - --log-level=debug
            - --
          env:
            - name: CF_API_TOKEN # or CF_API_KEY
              value: "PLACEHOLDER_EDNS_API_KEY" # change after each onboarding
