allow_k8s_contexts('')
image = 'registry.services.k8s.true.nl/onboarding/nodejs-example'
k8s_yaml('k8s/deployment.yaml')

docker_build(image, '.',
  live_update=[
    # when package.json changes, we need to do a full build
    fall_back_on(['package.json', 'package-lock.json']),
    # Map the local source code into the container under /src
    sync('src/', '/'),
  ]
)
k8s_resource('nodejs-example', port_forwards=3000)
