allow_k8s_contexts('')
image = 'registry.services.k8s.true.nl/onboarding/php-fastcgi-demo'
k8s_yaml(['k8s/deployment.yaml', 'k8s/configmap.yaml', 'k8s/ingress.yaml', 'k8s/service.yaml'])

docker_build(image, '.',
  live_update=[
    # when package.json changes, we need to do a full build
    fall_back_on(['package.json', 'package-lock.json']),
    # Map the local source code into the container under /src
    sync('src/', '/usr/src/myapp'),
  ]
)
# not needed.
#k8s_resource('nodejs-example', port_forwards=3000)
