apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  finalizers:
    - delete-pxc-pods-in-order
  name: cluster1
spec:
  backup:
    image: 'percona/percona-xtradb-cluster-operator:1.1.0-backup'
    schedule:
      - keep: 3
        name: sat-night-backup
        schedule: 0 0 * * 6
        storageName: s3-us-west
      - keep: 5
        name: daily-backup
        schedule: 0 0 * * *
        storageName: fs-pvc
    storages:
      fs-pvc:
        type: filesystem
        volume:
          persistentVolumeClaim:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 6Gi
      s3-us-west:
        s3:
          bucket: db-backups
          credentialsSecret: my-cluster-name-backup-s3
          region: us-west-2
        type: s3
  pmm:
    enabled: false
    image: 'perconalab/pmm-client:1.17.1'
    serverHost: monitoring-service
    serverUser: pmm
  proxysql:
    affinity:
      antiAffinityTopologyKey: kubernetes.io/hostname
    enabled: true
    gracePeriod: 30
    image: 'percona/percona-xtradb-cluster-operator:1.1.0-proxysql'
    podDisruptionBudget:
      maxUnavailable: 1
    resources:
      requests:
        cpu: 600m
        memory: 1G
    size: 3
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 2Gi
  pxc:
    affinity:
      antiAffinityTopologyKey: kubernetes.io/hostname
    allowUnsafeConfigurations: false
    gracePeriod: 600
    image: 'percona/percona-xtradb-cluster-operator:1.1.0-pxc'
    podDisruptionBudget:
      maxUnavailable: 1
    resources:
      requests:
        cpu: 600m
        memory: 1G
    size: 3
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 6Gi
  secretsName: my-cluster-secrets
  sslInternalSecretName: my-cluster-ssl-internal
  sslSecretName: my-cluster-ssl
